include_guard(GLOBAL)

option(CHRONOS_BUILD_TESTS "Build ChronosDB unit tests" ON)
option(CHRONOS_BUILD_BENCHMARKS "Build ChronosDB microbenchmarks" OFF)
option(CHRONOS_BUILD_FUZZERS "Build ChronosDB libFuzzer targets" OFF)
option(CHRONOS_ENABLE_ASAN "Enable AddressSanitizer on ChronosDB targets" OFF)
option(CHRONOS_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer on ChronosDB targets" OFF)
option(CHRONOS_ENABLE_TSAN "Enable ThreadSanitizer on ChronosDB targets" OFF)
option(CHRONOS_ENABLE_CLANG_TIDY "Run clang-tidy while compiling ChronosDB targets" OFF)
option(CHRONOS_WARNINGS_AS_ERRORS "Treat ChronosDB target warnings as errors" OFF)
option(CHRONOS_ENABLE_IO_URING "Build the optional Linux liburing reactor backend" OFF)
option(CHRONOS_ENABLE_ARROW_INTEROP "Build Arrow IPC and Parquet import/export support" OFF)
