include_guard(GLOBAL)

function(chronos_validate_sanitizers)
  if(CHRONOS_ENABLE_TSAN AND (CHRONOS_ENABLE_ASAN OR CHRONOS_ENABLE_UBSAN))
    message(FATAL_ERROR "ThreadSanitizer must run separately from AddressSanitizer and UndefinedBehaviorSanitizer")
  endif()

  if(CHRONOS_ENABLE_ASAN OR CHRONOS_ENABLE_UBSAN OR CHRONOS_ENABLE_TSAN)
    if(MSVC OR NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
      message(FATAL_ERROR "Requested sanitizers require a supported GCC, Clang, or AppleClang toolchain")
    endif()
  endif()
endfunction()

function(chronos_enable_sanitizers target)
  set(sanitizers "")
  if(CHRONOS_ENABLE_ASAN)
    list(APPEND sanitizers address)
  endif()
  if(CHRONOS_ENABLE_UBSAN)
    list(APPEND sanitizers undefined)
  endif()
  if(CHRONOS_ENABLE_TSAN)
    list(APPEND sanitizers thread)
  endif()

  if(sanitizers)
    list(JOIN sanitizers "," sanitizer_list)
    target_compile_options("${target}" PRIVATE "-fsanitize=${sanitizer_list}" -fno-omit-frame-pointer)
    target_link_options("${target}" PRIVATE "-fsanitize=${sanitizer_list}" -fno-omit-frame-pointer)
  endif()
endfunction()
